### ISSUE TITLE
I wanna share this RMHM guide i made (copied/cut pasted)

### ISSUE THREAD

**Issue by AntiScrewdriver** [Kaseaa/tera-guide#11]
https://github.com/AntiScrewdriver/Tera-RMHM-Guide/blob/master/Tera-RMHM-Guide

I don't know how else to share this, so im posting here.
Its a guide for the third boss, mostly from meelee's perspective.

"Left hand, Right hand" is there because its how you can tell a tail slam is coming.
If she starts with Left -> Right, then right after that is a tail Slam.

I dont know programming, if did i would probably do something like
( if "right hand" after "left hand" 
then on "right hand" say : "Tail Slam!" )
Also i dont know how to combine the already existing RMHM first boss guide with this one.

In any case barely anyone does RMHM nowadays, and its hard to learn. This helped me, so i hope its gonna help someone else.

**Comment by Kasea** [comment]
added
