### ISSUE TITLE
CSNM in/Out bugged mechanic

### ISSUE THREAD

**Issue by irinabbelina** [Kaseaa/tera-guide#17]
Hello.

Since Draakon Arena patch , CSNM In/Out mechanic got bugged.

After  boss is around 60-50 % HP  the In/Out mechanic just  reverses..  In become out/ Out becomes in...and sometimes  It's  accurate.

My friends that use the tera guide master experience such issue since release of the patch.

In/Out its not accurate no more after some time in boss fight.

**Comment by justkeepquiet** [comment]
This bug fixed on my guide mod fork https://github.com/hsdn/tera-guide/issues/4

**Comment by irinabbelina** [comment]
I have 0 reasons to lie.  It happend to many times after patch hit.. that was 2 days ago.  My friends experience the same.   I will record if it happens again.

I never had this In/Out issue... But since 2 days ( patch arival) its constant


Ur guide is Tera-Guide Master yes?? maybe im using wrong guide??  could u link me ur guide pls?

**Comment by justkeepquiet** [comment]
Yes, most of the guides do not work now. 
But we fixed the bug after the patch was released on EU.

Fixed guide module here https://github.com/hsdn/tera-guide

**Comment by irinabbelina** [comment]
ty vm..il check it out and let u know if any more issues..  amazing guide..one of my fav <3

**Comment by Kasea** [comment]
dude, this repo doesn't have even have CSNM???

also @shindmitry when you forking from here instead of from random repo? smh
