### ISSUE TITLE
tera-guide

### ISSUE THREAD

**Issue by Massouille38** [Kaseaa/tera-guide#18]
Bonjour,
![Capture d’écran 2021-09-09 163933](https://user-images.githubusercontent.com/90772944/133436735-95813e55-7c1d-4edc-b7c7-24673d94b242.png)
Je ne peux pas installer  le module "tera-guilde" dans My Mods de Toolbox.
Pouvez-vous me trouver une solution.
Je vous remercie d'avance

**Comment by Kasea** [comment]
I do not speak french.
