### ISSUE TITLE
Keep same style on AA guides

### ISSUE THREAD

**Issue by MeowyMeow** [Kaseaa/tera-guide#3]
Hi, AANM/HM guides have different styles on callouts even for same bosses. For some attacks it says where to go for safety, and for other attacks it says where the boss will hit. So it's rather confusing.
for example, Backstep+donuts, stay in, get out
Should just call out IN -> OUT. 
and then enraged Massive In-Out Big AoE+Inner AoE+Outer AoE
should just call dodge -> OUT -> IN.
That way it keeps a standard and becomes less confusing. Always calling out the same thing (where to go) instead of alternating between calling where to go and where mechanic will hit.

**Comment by Kasea** [comment]
Feel free to fix it yourself and upload it. I didn't write the AA guides, so I'm not gonna touch that.
