### ISSUE TITLE
error: Long constructor is no longer supported, use BigInt type instead

### ISSUE THREAD

**Issue by keybladesora** [Kaseaa/tera-guide#4]
Can't use the module!

**Comment by Kasea** [comment]
maybe start using a real proxy? using pinkie's proxy was your first mistake. 

https://discord.gg/maqBmJV

If you install Caali's tera-proxy, it will auto update and download the latest opcodes, packet definitions, and compatible modules - meaning you'll never have to manually update anything!
A more detailed explanation can be found in the #info and #proxy channels of the linked discord.

**Comment by Night31** [comment]
WP kasea
